name: E2E Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: larament_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql, gd
          coverage: none

      - name: Copy environment file
        run: cp .env.example .env

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Configure database
        run: |
          php artisan config:cache
          php artisan migrate --force
          php artisan db:seed --force

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Start Laravel server
        run: php artisan serve --host=127.0.0.1 --port=8000 &
        env:
          APP_URL: http://127.0.0.1:8000

      - name: Wait for server
        run: |
          timeout 30 bash -c 'until curl -f http://127.0.0.1:8000; do sleep 1; done'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=http://127.0.0.1:8000
          install: false
          wait-on: 'http://127.0.0.1:8000'
          wait-on-timeout: 120
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Laravel logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: laravel-logs
          path: storage/logs
